### ISSUE TITLE
在别的板块如果选择了在PT板块发帖，则无法显示PT相关内容

### ISSUE THREAD

**Issue by ixiaofeng** [deatil/pt#1]
<img width="940" alt="2018-04-17 10 54 05" src="https://user-images.githubusercontent.com/6447924/38846209-cd1cf486-422d-11e8-9db1-c8cdb26f4023.png">
<img width="957" alt="2018-04-17 10 55 28" src="https://user-images.githubusercontent.com/6447924/38846222-de9cb458-422d-11e8-827f-98d173167cd6.png">

只有先进入到设置好的pt板块，然后才能正常显示
<img width="1028" alt="2018-04-17 10 56 11" src="https://user-images.githubusercontent.com/6447924/38846241-f78d51f2-422d-11e8-834e-b39e02a2650d.png">

**Comment by deatil** [comment]
这个目前是这样的，暂时还没有做跳转或者异步改变这些
