### ISSUE TITLE
关于PT

### ISSUE THREAD

**Issue by zhuanyessr** [deatil/pt#4]
请问大佬，您的联系方式多少呢？我telegram:https://t.me/lituzi

**Comment by deatil** [comment]
> 请问大佬，您的联系方式多少呢？我telegram:https://t.me/lituzi

怎么了？没有用telegram

**Comment by zhuanyessr** [comment]
您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持

**Comment by deatil** [comment]
> 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持

能问下，pt站是做哪方面的吗

**Comment by zhuanyessr** [comment]
> > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> 
> 能问下，pt站是做哪方面的吗

前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧

**Comment by deatil** [comment]
> > > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> > 
> > 
> > 能问下，pt站是做哪方面的吗
> 
> 前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧

好吧。用这个还不行吗？还需要加其他的东西吗？

**Comment by zhuanyessr** [comment]
> > > > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> > > 
> > > 
> > > 能问下，pt站是做哪方面的吗
> > 
> > 
> > 前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧
> 
> 好吧。用这个还不行吗？还需要加其他的东西吗？

暂时是够用，现在主要问题是您这个tracker必须和主站在同一个服务器吗？可以把他们分离吗？

**Comment by deatil** [comment]
> > > > > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> > > > 
> > > > 
> > > > 能问下，pt站是做哪方面的吗
> > > 
> > > 
> > > 前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧
> > 
> > 
> > 好吧。用这个还不行吗？还需要加其他的东西吗？
> 
> 暂时是够用，现在主要问题是您这个tracker必须和主站在同一个服务器吗？可以把他们分离吗？

分离好像不行。要分离的话可以再另一台服务器上放一份，数据库链接到主站或者数据库服务器。

**Comment by zhuanyessr** [comment]
> > > > > > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> > > > > 
> > > > > 
> > > > > 能问下，pt站是做哪方面的吗
> > > > 
> > > > 
> > > > 前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧
> > > 
> > > 
> > > 好吧。用这个还不行吗？还需要加其他的东西吗？
> > 
> > 
> > 暂时是够用，现在主要问题是您这个tracker必须和主站在同一个服务器吗？可以把他们分离吗？
> 
> 分离好像不行。要分离的话可以再另一台服务器上放一份，数据库链接到主站或者数据库服务器。

另外一台服务器搭建一样的论坛？

**Comment by deatil** [comment]
> > > > > > > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> > > > > > 
> > > > > > 
> > > > > > 能问下，pt站是做哪方面的吗
> > > > > 
> > > > > 
> > > > > 前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧
> > > > 
> > > > 
> > > > 好吧。用这个还不行吗？还需要加其他的东西吗？
> > > 
> > > 
> > > 暂时是够用，现在主要问题是您这个tracker必须和主站在同一个服务器吗？可以把他们分离吗？
> > 
> > 
> > 分离好像不行。要分离的话可以再另一台服务器上放一份，数据库链接到主站或者数据库服务器。
> 
> 另外一台服务器搭建一样的论坛？

对。不过还是麻烦，系统插件默认就是不支持分站的

**Comment by zhuanyessr** [comment]
> > > > > > > > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> > > > > > > 
> > > > > > > 
> > > > > > > 能问下，pt站是做哪方面的吗
> > > > > > 
> > > > > > 
> > > > > > 前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧
> > > > > 
> > > > > 
> > > > > 好吧。用这个还不行吗？还需要加其他的东西吗？
> > > > 
> > > > 
> > > > 暂时是够用，现在主要问题是您这个tracker必须和主站在同一个服务器吗？可以把他们分离吗？
> > > 
> > > 
> > > 分离好像不行。要分离的话可以再另一台服务器上放一份，数据库链接到主站或者数据库服务器。
> > 
> > 
> > 另外一台服务器搭建一样的论坛？
> 
> 对。不过还是麻烦，系统插件默认就是不支持分站的

好吧，大佬，您以后有计划做分离吗？

**Comment by deatil** [comment]
> > > > > > > > > 您有即时通讯联系方式吗？我想做个pt站，希望您能提供技术支持
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 能问下，pt站是做哪方面的吗
> > > > > > > 
> > > > > > > 
> > > > > > > 前期主要是想做国产/网络电视剧，后期如果人气可以，就计划增加海外剧
> > > > > > 
> > > > > > 
> > > > > > 好吧。用这个还不行吗？还需要加其他的东西吗？
> > > > > 
> > > > > 
> > > > > 暂时是够用，现在主要问题是您这个tracker必须和主站在同一个服务器吗？可以把他们分离吗？
> > > > 
> > > > 
> > > > 分离好像不行。要分离的话可以再另一台服务器上放一份，数据库链接到主站或者数据库服务器。
> > > 
> > > 
> > > 另外一台服务器搭建一样的论坛？
> > 
> > 
> > 对。不过还是麻烦，系统插件默认就是不支持分站的
> 
> 好吧，大佬，您以后有计划做分离吗？

现阶段暂时没有计划

**Comment by deatil** [comment]
先把这个issue关了，有其他想法再重开个issue
