### ISSUE TITLE
请问可以单独提取吗？

### ISSUE THREAD

**Issue by zhuanyessr** [deatil/pt#5]
请问可以单独把查看种子详情提取出来做一个插件吗？这样做BT站也能用得上，谢谢

**Comment by zhuanyessr** [comment]
就是能够解析帖子种子附件，显示种子文件列表这种

**Comment by deatil** [comment]
种子的详细信息，在详情里是有的。
重新写个列表页面放下就可以的，这种最好就是自己写个页面，用插件不是很合适

**Comment by zhuanyessr** [comment]
可以付费请您做个吗？谢谢

**Comment by deatil** [comment]
> 可以付费请您做个吗？谢谢

最近没做pt这方面的了，做的话现在估计也没时间
